From dba2e9c951a47c4193a779a934c5a2d415675b10 Mon Sep 17 00:00:00 2001
From: Ronan Abhamon <ronan.abhamon@vates.fr>
Date: Mon, 8 Mar 2021 13:25:28 +0100
Subject: [PATCH 036/180] fix(LinstorJournaler): ensure uri is not None during
 linstor.KV creation

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
---
 drivers/linstorjournaler.py | 13 ++++++++++---
 1 file changed, 10 insertions(+), 3 deletions(-)

diff --git a/drivers/linstorjournaler.py b/drivers/linstorjournaler.py
index 285012ca..3993f601 100755
--- a/drivers/linstorjournaler.py
+++ b/drivers/linstorjournaler.py
@@ -16,7 +16,8 @@
 #
 
 
-from linstorvolumemanager import get_controller_uri, LinstorVolumeManager
+from linstorvolumemanager import \
+  get_controller_uri, LinstorVolumeManager, LinstorVolumeManagerError
 import linstor
 import re
 import util
@@ -145,6 +146,10 @@ class LinstorJournaler:
         def connect(uri):
             if not uri:
                 uri = get_controller_uri()
+                if not uri:
+                    raise LinstorVolumeManagerError(
+                        'Unable to find controller uri...'
+                    )
             return linstor.KV(
                 LinstorVolumeManager._build_group_name(group_name),
                 uri=uri,
@@ -153,13 +158,15 @@ class LinstorJournaler:
 
         try:
             return connect(uri)
-        except linstor.errors.LinstorNetworkError:
+        except (linstor.errors.LinstorNetworkError, LinstorVolumeManagerError):
             pass
 
         return util.retry(
             lambda: connect(None),
             maxretry=10,
-            exceptions=[linstor.errors.LinstorNetworkError]
+            exceptions=[
+                linstor.errors.LinstorNetworkError, LinstorVolumeManagerError
+            ]
         )
 
     @staticmethod
